### ISSUE TITLE
老铁你这个玩意怎么用的呀？

### ISSUE THREAD

**Issue by siyehua** [antergone/palm-proxy#1]
我在vercel里设置了环境变量了，base_url  也设置了 vercel 给的网址了，但是会提示：
<img width="703" alt="image" src="https://github.com/antergone/palm-proxy/assets/9376247/85f76320-e3d9-40d2-a5ca-da79664b07fb">
看控制台：
<img width="494" alt="image" src="https://github.com/antergone/palm-proxy/assets/9376247/2e3466fb-fe7e-4b74-874f-e30a7eb738ef">

请问要怎么设置呢？我哪里有问题

**Comment by antergone** [comment]
1. 按照README中的部署流程将本项目部署到Vercel中，获得对应的服务地址
2. 在Vercel搭建的GeminiProChat项目设置中加入环境变量 `API_BASE_URL`,  并填入对应URL，例如: `https://xxx-proxy.vercel.app/`
3. 其余配置按照 [GeminiProChat](https://github.com/babaohuang/GeminiProChat)手册进行配置
